/**
 *  This file is part of the EGIL SCIM client.
 *
 *  Copyright (C) 2017-2019 Föreningen Sambruk
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.

 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.

 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef SIMPLESCIM_ERROR_STRING_H
#define SIMPLESCIM_ERROR_STRING_H

bool has_errors_to_print();

/**
 * Returns an error string that contains the latest error
 * message generated by SimpleSCIM or "No error" if no
 * error string has been set.
 */
const char *simplescim_error_string_get();

/**
 * Sets the prefix of the error string with 'prefix' as the
 * format string. If a message has been set, the prefix
 * will appear before the message with a colon and a space
 * appended. If no message has been set, the prefix will
 * appear as is. NULL signifies no prefix.
 */
void simplescim_error_string_set_prefix(const char *prefix, ...);

/**
 * Sets the message of the error string with 'message' as
 * the format string. NULL signifies no message.
 */
void simplescim_error_string_set_message(const char *message, ...);

/**
 * Sets the prefix of the error string with 'prefix' as the
 * format string and sets the message of the error string
 * to strerror(errno). NULL signifies no prefix.
 */
void simplescim_error_string_set_errno(const char *prefix, ...);

/**
 * Sets the prefix of the error string to 'prefix' and sets
 * the message of the error string to 'message'.
 * 'prefix' == NULL signifies no prefix and
 * 'message' == NULL signifies no message.
 */
void simplescim_error_string_set(const char *prefix,
                                 const char *message);

#endif
