#!/usr/bin/env bash
source "${BASH_SOURCE%/*}/ldap_vars"
docker exec $container ldapsearch -D $adminuser -w $adminpasswd -b 'dc=kommunen,dc=se' -o ldif-wrap=no -s children '(&(objectClass=*)(!(cn=admin))(!(cn=readonly)))' dn | grep '^dn: ' | awk '{print $2}' | docker exec --interactive $container ldapdelete -r -c -D $adminuser -w $adminpasswd &> /dev/null
# ldapdelete will return an error if we delete a child
# after it's parent (note that we use both -r and -c to
# get rid of everything).
# Hence we don't worry about errors from ldapdelete.
true
