#!/usr/bin/env bash
testroot="${BASH_SOURCE%/*}/.."

cert=$(mktemp /tmp/testcert.XXXXXX)
key=$(mktemp /tmp/testkey.XXXXXX)
# Add test_external_process to PATH so external process tests can find it
TEST_EP_PATH_ABS=$(cd ${testroot}/test_external_process && pwd)
export PATH="${TEST_EP_PATH_ABS}:${PATH}"

openssl req -x509 -newkey rsa:4096 -keyout $key -out $cert -days 1 -nodes -subj '/CN=localhost' &> /dev/null

if (($# > 0))
then
    testargs="-tests $1"
else
    testargs=""
fi

${testroot}/test_server_go/EGILTestServer/EGILTestServer \
  -cert $cert \
  -key $key \
  -testroot $testroot \
  -binary ${testroot}/../build/EgilSCIMClient \
  $testargs

exitstatus=$?

rm $cert
rm $key

exit ${exitstatus}
