#!/usr/bin/env bash
docker container stop kommunens-ldap > /dev/null 2>&1
docker container rm kommunens-ldap > /dev/null 2>&1
docker run --env LDAP_ORGANISATION="Kommunen" \
       --env LDAP_DOMAIN="kommunen.se" \
       --env LDAP_ADMIN_PASSWORD="verysecret" \
       --env LDAP_TLS=false \
       --env LDAP_READONLY_USER=true \
       --env LDAP_READONLY_USER_USERNAME=readonly \
       --env LDAP_READONLY_PASSWORD=readonly \
       -p 388:389 \
       --name kommunens-ldap \
       --detach \
       osixia/openldap:1.2.4
