#!/usr/bin/env bash
source "${BASH_SOURCE%/*}/ldap_vars"

bootstrap=$(mktemp /tmp/boostrap.ldif.XXXXXX)

cat > ${bootstrap} <<EOF
dn: cn=config
changetype: modify
replace: olcSizeLimit
olcSizeLimit: 2000

dn: olcDatabase={-1}frontend,cn=config
changetype: modify
replace: olcSizeLimit
olcSizeLimit: 2000
EOF

docker container stop $container > /dev/null 2>&1
docker container rm $container > /dev/null 2>&1
docker run --env LDAP_ORGANISATION="Kommunen" \
       --env LDAP_DOMAIN="kommunen.se" \
       --env LDAP_ADMIN_PASSWORD=$adminpasswd \
       --env LDAP_TLS=false \
       --env LDAP_READONLY_USER=true \
       --env LDAP_READONLY_USER_USERNAME=readonly \
       --env LDAP_READONLY_PASSWORD=readonly \
       -p $port:389 \
       --name $container \
       --detach \
       --volume ${bootstrap}:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif \
       osixia/openldap:1.2.4 \
       --copy-service

rm ${bootstrap}
